name: Test

on:
  workflow_call:
    inputs:
      USE_DOTNET_7:
        required: false
        default: false
        type: boolean
    secrets:
      PRIVATE_NUGET_USERNAME:
        required: true
      PRIVATE_NUGET_PAT:
        required: true

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PRIVATE_NUGET_USERNAME: ${{ secrets.PRIVATE_NUGET_USERNAME }}
      PRIVATE_NUGET_PAT: ${{ secrets.PRIVATE_NUGET_PAT }}
      USE_DOTNET_7: ${{ inputs.USE_DOTNET_7 }}
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.x
        if: ${{ env.USE_DOTNET_7 == 'false'  }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Setup .NET 7.x
        if: ${{ env.USE_DOTNET_7 == 'true' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Run unit tests
        run: dotnet test